---
- name: Add apt key for nginx repository
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: Adding nginx repository
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
    state: present

- name: Installing nginx package
  apt:
    name: "nginx={{ nginx_version }}"
    state: present
    update_cache: yes
